/**
 * Product slugs that have images in public/images/products/.
 * Generated by: npm run generate:image-manifest
 * Products not in this set show the illustration (vial SVG + label) instead.
 */
export const PRODUCT_IMAGE_SLUGS = new Set(["glp-1-semaglutide","glp-1-tirzepatide","glp-1-retatrutide","aod-9604","sermorelin","tesamorelin","ipamorelin","cjc-1295-no-dac","igf-1-lr3","follistatin-344","bpc-157","tb500","wolverine-stack","glow-42","glow-70","klow-80","ghk-cu","hcg","gonadorelin","kisspeptin","pt-141","epitalon","mots-c","dsip","oxytocin","selank","semax","bacteriostatic-water","insulin-syringes","comprehensive-100-biomarker-panel","metabolic-diabetes-panel","cardiovascular-health-panel","hormonal-health-panel","thyroid-complete-panel","inflammation-immune-panel","nutrient-vitamin-panel","liver-kidney-function-panel","medical-review","glutathione","l-carnitine","telemedicine","vip-membership"]);
