/**
 * Product slugs that have images in public/images/products/.
 * Generated by: npm run generate:image-manifest
 * Products not in this set show the illustration (vial SVG + label) instead.
 */
export const PRODUCT_IMAGE_SLUGS = new Set(["aod-9604","bacteriostatic-water","bpc-157","cardiovascular-health-panel","cjc-1295-no-dac","comprehensive-100-biomarker-panel","dsip","epitalon","follistatin-344","ghk-cu","glow-42","glow-70","glp-1-retatrutide","glp-1-semaglutide","glp-1-tirzepatide","glutathione","gonadorelin","hcg","hormonal-health-panel","igf-1-lr3","inflammation-immune-panel","insulin-syringes","ipamorelin","kisspeptin","klow-80","l-carnitine","lathmized-nad-maintenance","lathmized-nad-medical","liver-kidney-function-panel","medical-review","metabolic-diabetes-panel","mots-c","nutrient-vitamin-panel","oxytocin","pt-141","selank","semax","sermorelin","tb500","telemedicine","tesamorelin","thyroid-complete-panel","vip-membership","wolverine-stack"]);
